- name: Disable swap 
  command: "swapoff -a"
- name: verifying that /etc/fstab do not contain swap
  command: "grep -i swap /etc/fstab"
  register: result
  failed_when:
   - result.rc == 0
- name: Disable SELinux
  selinux:
   state: disabled