- name: Copy a repository file to install k8s
  copy:
    src: "kubernetes.repo"
    dest: "/etc/yum.repos.d/kubernetes.repo"
    owner: root
    group: root
    mode: '0644'

- name: Install k8s packages.
  yum:
    name: ['kubelet', 'kubeadm', 'kubectl' ]
    state: present
    update_cache: True

- name: Starting and enable k8s service
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Delete container file
  file:
    path: "/etc/containerd/config.toml"
    state: absent

- name: restarting containerd 
  service:
     name: containerd
     state: restarted
     enabled: yes
     
- name: Copy a k8s.config file
  copy:
    src: "k8s.conf"
    dest: "/etc/modules-load.d/k8s.conf"
    owner: root
    group: root
    mode: '0644'

- name: Copy a sysctl k8s.config file required by setup, params persist across reboots
  copy:
    src: "sysctl.d_k8s.conf"
    dest: "/etc/sysctl.d/k8s.conf"
    owner: root
    group: root
    mode: '0644'

- name: Post running modprobe for overlay and br_netfilter
  command: "{{ item }}"
  with_items:
     - "modprobe overlay"
     - "modprobe br_netfilter"
     - "sysctl --system"

